import java.io.IOException;
import javax.swing.JOptionPane;

public class GUI1 extends javax.swing.JFrame {

    String s1;
    private String s2;
    /**
     * Creates new form GUI1
     */
    public GUI1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Predictive Spell Check");

        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        b1.setText("Go !!!");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(540, 260, 60, 30);

        t1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(80, 30, 400, 23);

        l3.setBackground(new java.awt.Color(153, 153, 153));
        l3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l3.setText("  Third Prediction");
        jPanel1.add(l3);
        l3.setBounds(480, 160, 120, 30);

        l2.setBackground(new java.awt.Color(51, 255, 51));
        l2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l2.setText("Second Prediction");
        jPanel1.add(l2);
        l2.setBounds(240, 160, 150, 30);

        l1.setBackground(new java.awt.Color(153, 153, 153));
        l1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l1.setText("First Prediction");
        l1.setToolTipText("");
        jPanel1.add(l1);
        l1.setBounds(20, 160, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/android_4_2_pc_keyboard.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(4, 4, 600, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void t1ActionPerformed(java.awt.event.ActionEvent evt) {
                      String  s2= t1.getText();
                      l3.setText(s2);
    
    }
    public void b1ActionPerformed(java.awt.event.ActionEvent evt) {
         
       /* public void start ()
   {
     
      {
         t = new Thread (this, threadName);
         t.start ();
        t.new1();
        t.new2();
        t.new3();
      }
   }       */
         /* l1.setText("hello");
         l2.setText("hey");
         l3.setText("hi"); */
         boolean t;
        s2= t1.getText();
        try {
            t=new1(s2);
           
        } catch (Exception e) {
        }    
        try {
            new2(s2);
        } catch (Exception e1) {
        }    
        try {
            new3(s2);
        } catch (Exception e2) {
        }    
        
        
    }                                  

   
    public static void main(String args[])
    {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }  

    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI1().setVisible(false); // after login this will be shhown
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

    public boolean new1(String s2) throws Exception {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
     
        { String pr1;
        boolean valid = false;
         
         
            valid = new JavaSpellChecker().checkSpelling(s2);  // ?? may be calling function without creaating object
           //JOptionPane.showMessageDialog(this," function checker ended ");
       
             if(valid==true)
             {  JOptionPane.showMessageDialog(this," Found in the dictionary ");
                 l1.setText(s2);}
        
             else if(valid == false)
           {
               //System.out.println(" prediction started ");
                  //String pr1;
               int l=s2.length();
               pr1=s2.substring(0,l-1) ;
        
               //System.out.println(" First prediction "+ pr1);
                //sleep.new1();
               new1(pr1); 
           }
                   
    
    }
       return true;
    }
    
    public boolean new2(String s2) throws IOException {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
     
        { String pr2;
        boolean valid = false;
        
         
            valid = new JavaSpellChecker().checkSpelling(s2);  // ?? may be calling function without creaating object
           //JOptionPane.showMessageDialog(this," function checker ended ");
       
             if(valid==true)
             {l2.setText(s2);}
        
             else if(valid == false)
           {
               //System.out.println(" prediction started ");
                  //String pr1;
               int ll=s2.length();
               pr2=s2.substring(0,ll-2) ;
        
               //System.out.println(" First prediction "+ pr1);
               //sleep.new2();
               new2(pr2); 
           }
                   
    
    }
       return true;
    
    }
    
    
    public boolean new3(String s2) throws IOException {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
     
         { String pr2;
        boolean valid = false;
        
         
            valid = new JavaSpellChecker().checkSpelling(s2);  // ?? may be calling function without creaating object
           //JOptionPane.showMessageDialog(this," function checker ended ");
       
             if(valid==true)
             {l3.setText(s2);}
        
             else if(valid == false)
           {
               //System.out.println(" prediction started ");
                  //String pr1;
               int lll=s2.length();
               pr2=s2.substring(0,lll-2) ;
        
               //System.out.println(" First prediction "+ pr1);
               //sleep.new2();
               new3(pr2); 
           }
                   
    
    }
       return true;
    
    }
    
}


